-- MySQL Script generated by MySQL Workbench
-- Fri Dec 13 15:23:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema restaurant_reservation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema restaurant_reservation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `restaurant_reservation` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `restaurant_reservation` ;

-- -----------------------------------------------------
-- Table `restaurant_reservation`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_reservation`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('CLIENT', 'ADMIN') NOT NULL DEFAULT 'ADMIN',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_id` (`num_id` ASC) VISIBLE,
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_reservation`.`tables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_reservation`.`tables` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `num_table` INT NOT NULL,
  `capacity` INT NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `num_table` (`num_table` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `restaurant_reservation`.`reservations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `restaurant_reservation`.`reservations` (
  `id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `table_id` INT NOT NULL,
  `reservation_time` DATETIME NOT NULL,
  `status` ENUM('CONFIRMED', 'CANCELED') NULL DEFAULT 'CONFIRMED',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_user_num_idx` (`user_id` ASC) VISIBLE,
  INDEX `id_table_num_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `id_user_num`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant_reservation`.`users` (`num_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_table_num`
    FOREIGN KEY (`table_id`)
    REFERENCES `restaurant_reservation`.`tables` (`num_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



CREATE TABLE IF NOT EXISTS `restaurant_reservation`.`reservations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `table_id` INT NOT NULL,
  `reservation_time` DATETIME NOT NULL,
  `status` ENUM('CONFIRMED', 'CANCELED') NULL DEFAULT 'CONFIRMED',
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `id_user_num_idx` (`user_id` ASC) VISIBLE,
  INDEX `id_table_num_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `id_user_num`
    FOREIGN KEY (`user_id`)
    REFERENCES `restaurant_reservation`.`users` (`num_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_table_num`
    FOREIGN KEY (`table_id`)
    REFERENCES `restaurant_reservation`.`tables` (`num_table`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
